layout_spectrum: 0.4684858
typography_spectrum: 0.586743
color:
  saturation: 0.08189322
  lightness: 0.702003
  brandStrength: 0.7537258
  rhythmicContrast: 0.9944732
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Climb Consulting
