collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.08189322
  brandStrength: 0.7616488
  lightness: 0.702003
  brandColors:
    - '#030302'
    - '#9B874C'
    - '#524C32'
    - '#F7F7F7'
    - '#FFE088'
  rhythmicContrast: 0.9050179
typography_spectrum: 0.586743
layout_spectrum: 0.06989247
name: Climb Consulting
